admin_login:
    pattern: /login
    defaults: { _controller: BackendBundle:Backend:login }

admin_login_check:
    pattern: /login_check

admin_logout:
    pattern: /logout

admin_register:
    pattern: /register
    defaults: { _controller: BackendBundle:Backend:register }

admin:
    pattern: /
    defaults: #{ _controller: BackendBundle:Backend:example }
        _controller: FrameworkBundle:Redirect:redirect
        route: admin_index
        permanent: true # this is for 301

admin_index:
    pattern: /dashboard
    defaults: { _controller: BackendBundle:Backend:index }

admin_categories:
    resource: "@BackendBundle/Resources/config/routing/category.yml"
    prefix: /category/

admin_subcategories:
    resource: "@BackendBundle/Resources/config/routing/subcategory.yml"
    prefix: /subcategory/

admin_users:
    resource: "@BackendBundle/Resources/config/routing/user.yml"
    prefix: /user/

admin_items:
    resource: "@BackendBundle/Resources/config/routing/item.yml"
    prefix: /product/

admin_orders:
    resource: "@BackendBundle/Resources/config/routing/order.yml"
    prefix: /order/

admin_manufacturers:
    resource: "@BackendBundle/Resources/config/routing/manufacturer.yml"
    prefix: /manufacturer/

admin_shipment_options:
    resource: "@BackendBundle/Resources/config/routing/shipment.yml"
    prefix: /shipment/

admin_recent_orders:
    pattern: /recent-orders
    defaults: { _controller: BackendBundle:Backend:getRecentOrders }

admin_billing_settings_index:
    pattern: /data-billing
    defaults: { _controller: BackendBundle:DataBilling:index }